src/Entity/Stagiaire.php
<?php

namespace App\Entity;

use App\Repository\StagiaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Length;

#[ORM\Entity(repositoryClass: StagiaireRepository::class)]
class Stagiaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column()]
    #[Length(min: 2, max: 20, minMessage: "Il faut plus de 2 caractères.", maxMessage: "Pas plus de 20 caractères")]
    private ?string $nom = null;

    #[ORM\Column()]
    #[Length(min: 2, max: 20, minMessage: "Il faut plus de 2 caractères.", maxMessage: "Pas plus de 20 caractères")]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 60, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_inscription = null;

    #[ORM\Column(length: 60)]
    #[Email]
    private ?string $email = null;

    /**
     * @var Collection<int, Stage>
     */
    #[ORM\ManyToMany(targetEntity: Stage::class, mappedBy: 'stagiaires')]
    private Collection $stages;

    public function __construct()
    {
        $this->stages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): static
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, Stage>
     */
    public function getStages(): Collection
    {
        return $this->stages;
    }

    public function addStage(Stage $stage): self
    {
        if (!$this->stages->contains($stage)) {
            $this->stages->add($stage);
            $stage->addStagiaire($this);
        }

        return $this;
    }

    public function removeStage(Stage $stage): self
    {
        if ($this->stages->removeElement($stage)) {
            $stage->removeStagiaire($this);
        }

        return $this;
    }
}

src/Form/StagiaireType.php
<?php

namespace App\Form;

use App\Entity\Stage;
use App\Entity\Stagiaire;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StagiaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('adresse')
            ->add('code_postal')
            ->add('ville')
            ->add('email')
        ;

        if ($options['hide_mdp']) {
            $builder->add('mdp', HiddenType::class, [
                'data' => $options['mdp_actuel'],
                'mapped' => false,
            ]);
        } else {
            $builder->add('mdp', PasswordType::class, [
                'label' => 'Mot de passe',
                'mapped' => false,
                'required' => true,
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Stagiaire::class,
            'hide_mdp' => false,
            'mdp_actuel' => null,
        ]);
    }
}

src/Controller/StagiaireController.php
<?php

namespace App\Controller;

use App\Entity\Stagiaire;
use App\Entity\User;
use App\Form\StagiaireType;
use App\Repository\StagiaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

final class StagiaireController extends AbstractController
{
    #[Route('/stagiaire', name: 'app_stagiaire_index', methods: ['GET'])]
    public function index(StagiaireRepository $stagiaireRepository): Response
    {
        return $this->render('stagiaire/index.html.twig', [
            'stagiaires' => $stagiaireRepository->findAll(),
        ]);
    }

    #[Route('/stagiaire/ajout_stagiaire', name: 'app_stagiaire_new', methods: ['GET', 'POST'])]
    public function new(Request $request,
                        EntityManagerInterface $entityManager,
                        UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $stagiaire = new Stagiaire();
        $user = new User();

        $form = $this->createForm(StagiaireType::class, $stagiaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setNom($stagiaire->getNom());
            $user->setPrenom($stagiaire->getPrenom());
            $user->setEmail($stagiaire->getEmail());
            $user->setRoles(['ROLE_STAGIAIRE']);

            $mdp = $form->get('mdp')->getData();
            $user->setPassword($userPasswordHasher->hashPassword($user, $mdp));
            $user->setIdStagiaire($stagiaire);
            $entityManager->persist($user);

            $stagiaire->setDateInscription(new \DateTime());
            $entityManager->persist($stagiaire);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_dashboard', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('stagiaire/new.html.twig', [
            'stagiaire' => $stagiaire,
            'form' => $form,
        ]);
    }

    #[Route('/stagiaire/{id}', name: 'app_stagiaire_show', methods: ['GET'])]
    public function show(Stagiaire $stagiaire): Response
    {
        return $this->render('stagiaire/show.html.twig', [
            'stagiaire' => $stagiaire,
        ]);
    }

    #[Route('/stagiaire/{id}/modification_compte', name: 'app_stagiaire_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Stagiaire $stagiaire, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $stagiaireUser = $entityManager->getRepository(User::class)->findByStagiaire($stagiaire);

        $form = $this->createForm(StagiaireType::class, $stagiaire, [
            'hide_mdp' => true,
            'mdp_actuel' => $stagiaireUser->getPassword(),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $stagiaireUser->setNom($stagiaire->getNom());
            $stagiaireUser->setPrenom($stagiaire->getPrenom());
            $stagiaireUser->setEmail($stagiaire->getEmail());

            $entityManager->persist($stagiaireUser);
            $entityManager->persist($stagiaire);
            $entityManager->flush();

            if($user->getRoles()[0] == "ROLE_STAGIAIRE"){
                return $this->redirectToRoute('app_stagiaire_dashboard', [], Response::HTTP_SEE_OTHER);
            } else {
                return $this->redirectToRoute('app_stagiaire_index', [], Response::HTTP_SEE_OTHER);
            }

        }

        return $this->render('stagiaire/edit.html.twig', [
            'stagiaire' => $stagiaire,
            'form' => $form,
        ]);
    }

    #[Route('stagiaire/{id}/delete', name: 'app_stagiaire_delete', methods: ['POST'])]
    public function delete(Request $request, TokenStorageInterface $tokenStorage, Stagiaire $stagiaire, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $stagiaireUser = $entityManager->getRepository(User::class)->findByStagiaire($stagiaire);

        if ($this->isCsrfTokenValid('delete'.$stagiaire->getId(), $request->get('_token'))){

            $stagiaireUser->setIdStagiaire(null);
            $entityManager->persist($stagiaireUser);
            $entityManager->flush();

            if($user->getRoles()[0] == "ROLE_STAGIAIRE"){
                $tokenStorage->setToken(null);
                $request->getSession()->invalidate();
            }

            if ($stagiaire) {
                $entityManager->remove($stagiaire);
                $entityManager->flush();
            }

            $entityManager->remove($stagiaireUser);
            $entityManager->flush();
        }

        if($user->getRoles()[0] == "ROLE_STAGIAIRE"){
            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        } else {
            return $this->redirectToRoute('app_stagiaire_index', [], Response::HTTP_SEE_OTHER);
        }

    }
}

templates/stagiaire/_delete_form.html.twig
<form method="post" action="{{ path('app_stagiaire_delete', {'id': stagiaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stagiaire.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/stagiaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h2 class="text-center">Modification des données personnelles</h2>
        <div>
                {{ form_start(form) }}

                {{ form_row(form.nom) }}
                {{ form_row(form.prenom) }}
                {{ form_row(form.email) }}
                {{ form_row(form.adresse) }}
                {{ form_row(form.code_postal) }}
                {{ form_row(form.ville) }}
            <button class="btn btn-outline-dark">{{ button_label|default('Sauvegarder') }}</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/stagiaire/index.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ path('app_admin_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
    <a href="{{ path('app_professeur_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des professeurs</a>
    <a href="{{ path('app_stagiaire_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des stagiaires</a>
    <a href="{{ path('app_matiere_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des matières</a>
    <a href="{{ path('app_stage_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des stages</a>
{% endblock %}
{% block body %}
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Adresse</th>
                <th>Code postal</th>
                <th>Ville</th>
                <th>Date d'inscription</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for stagiaire in stagiaires %}
                <tr>
                    <td>{{ stagiaire.nom }}</td>
                    <td>{{ stagiaire.prenom }}</td>
                    <td>{{ stagiaire.adresse }}</td>
                    <td>{{ stagiaire.codePostal }}</td>
                    <td>{{ stagiaire.ville }}</td>
                    <td>{{ stagiaire.dateInscription ? stagiaire.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ stagiaire.email }}</td>
                    <td>
                        <a href="{{ path('app_stagiaire_edit', {'id': stagiaire.id}) }}" class="btn btn-outline-dark m-2">Modifier</a>
                        {{ include('stagiaire/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">Pas de stagiaires inscrits à la plateforme</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/stagiaire/new.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ path('app_admin_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
{% endblock %}
{% block body %}
    <div class="container">
        <h2 class="mb-4 text-center">Création d'un profil stagiaire</h2>

        <div>
            {{ form_start(form) }}
                {{ form_row(form.nom) }}
                {{ form_row(form.prenom) }}
                {{ form_row(form.adresse) }}
                {{ form_row(form.ville) }}
                {{ form_row(form.code_postal) }}
                {{ form_row(form.email) }}
                {{ form_row(form.mdp) }}
            <button class="btn btn-outline-dark">{{ button_label|default('Créer') }}</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/stagiaire/show.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ path('app_stagiaire_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
{% endblock %}
{% block body %}
<div class="container">
    <h2 class="mb-4 text-center">Mes informations</h2>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ stagiaire.nom }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ stagiaire.prenom }}</td>
            </tr>

            {% if stagiaire.adresse %}
                <tr>
                    <th>Adresse</th>
                    <td>{{ stagiaire.adresse }}</td>
                </tr>
            {% else %}
                <tr class="table-warning">
                    <th>Adresse</th>
                    <td>A définir</td>
                </tr>
            {% endif %}

            {% if stagiaire.codePostal %}
                <tr>
                    <th>Code postal</th>
                    <td>{{ stagiaire.codePostal }}</td>
                </tr>
            {% else %}
                <tr class="table-warning">
                    <th>Code postal</th>
                    <td>A définir</td>
                </tr>
            {% endif %}

            {% if stagiaire.ville %}
                <tr>
                    <th>Ville</th>
                    <td>{{ stagiaire.ville }}</td>
                </tr>
            {% else %}
                <tr class="table-warning">
                    <th>Ville</th>
                    <td>A définir</td>
                </tr>
            {% endif %}

            <tr>
                <th>Email</th>
                <td>{{ stagiaire.email }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{{ path('app_stagiaire_edit', {'id': stagiaire.id}) }}" class="btn btn-outline-dark">Modifier</a>
</div>
    <hr class="m-4">
    <div class="card border-warning p-2 m-4 text-center">
        Cette action supprimeras définitivement le compte !
    </div>
    <div class="d-flex justify-content-center">
        {{ include('stagiaire/_delete_form.html.twig') }}
    </div>
{% endblock %}