src/Entity/Matiere.php
<?php

namespace App\Entity;

use App\Repository\MatiereRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Unique;

#[ORM\Entity(repositoryClass: MatiereRepository::class)]
class Matiere
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $code_matiere = null;

    #[ORM\Column(length: 60, unique: true)]
    #[NotBlank]
    private ?string $libelle = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    /**
     * @var Collection<int, Stage>
     */
    #[ORM\ManyToMany(targetEntity: Stage::class, inversedBy: 'matieres', cascade: ['persist', 'remove'])]
    #[ORM\JoinTable(name: 'matiere_stage')]
    private Collection $stages;

    /**
     * @var Collection<int, Professeur>
     */
    #[ORM\OneToMany(targetEntity: Professeur::class, mappedBy: 'matiere', cascade: ['persist', 'remove'])]
    private Collection $professeurs;

    public function __construct()
    {
        $this->stages = new ArrayCollection();
        $this->professeurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeMatiere(): ?string
    {
        return $this->code_matiere;
    }

    public function setCodeMatiere(string $code_matiere): static
    {
        $this->code_matiere = $code_matiere;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Stage>
     */
    public function getStages(): Collection
    {
        return $this->stages;
    }

    public function addStage(Stage $stage): self
    {
        if (!$this->stages->contains($stage)) {
            $this->stages->add($stage);
        }

        return $this;
    }

    public function removeStage(Stage $stage): self
    {
        $this->stages->removeElement($stage);
        return $this;
    }

    /**
     * @return Collection<int, Professeur>
     */
    public function getProfesseurs(): Collection
    {
        return $this->professeurs;
    }

    public function addProfesseur(Professeur $professeur): static
    {
        if (!$this->professeurs->contains($professeur)) {
            $this->professeurs->add($professeur);
            $professeur->setMatiere($this);
        }

        return $this;
    }

    public function removeProfesseur(Professeur $professeur): static
    {
        if ($this->professeurs->removeElement($professeur)) {
            // set the owning side to null (unless already changed)
            if ($professeur->getMatiere() === $this) {
                $professeur->setMatiere(null);
            }
        }

        return $this;
    }
}

src/Form/MatiereType.php
<?php

namespace App\Form;

use App\Entity\Matiere;
use App\Entity\Stage;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MatiereType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Matiere::class,
        ]);
    }
}

src/Controller/MatiereController.php
<?php

namespace App\Controller;

use App\Entity\Matiere;
use App\Form\MatiereType;
use App\Repository\MatiereRepository;
use App\Service\GenerateCode;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class MatiereController extends AbstractController
{
    #[Route('/matiere', name: 'app_matiere_index', methods: ['GET'])]
    public function index(MatiereRepository $matiereRepository): Response
    {
        return $this->render('matiere/index.html.twig', [
            'matieres' => $matiereRepository->findAll(),
        ]);
    }

    #[Route('/matiere/ajout_matiere', name: 'app_matiere_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $matiere = new Matiere();
        $code = new GenerateCode($entityManager);

        $form = $this->createForm(MatiereType::class, $matiere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $matiere->setCodeMatiere($code->code());
            $entityManager->persist($matiere);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_dashboard', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('matiere/new.html.twig', [
            'matiere' => $matiere,
            'form' => $form,
        ]);
    }

    #[Route('/matiere/{id}', name: 'app_matiere_show', methods: ['GET'])]
    public function show(Matiere $matiere): Response
    {
        return $this->render('matiere/show.html.twig', [
            'matiere' => $matiere,
        ]);
    }

    #[Route('/matiere/{id}/modification_matiere', name: 'app_matiere_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Matiere $matiere, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MatiereType::class, $matiere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_matiere_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('matiere/edit.html.twig', [
            'matiere' => $matiere,
            'form' => $form,
        ]);
    }

    #[Route('/matiere/{id}/suppression_matiere', name: 'app_matiere_delete', methods: ['POST'])]
    public function delete(Request $request, Matiere $matiere, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$matiere->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($matiere);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_matiere_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/matiere/_delete_form.html.twig
<form method="post" action="{{ path('app_matiere_delete', {'id': matiere.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ matiere.id) }}">
    <button class="btn btn btn-danger">Supprimer</button>
</form>

templates/matiere/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/matiere/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Matiere{% endblock %}

{% block body %}
    <h1>Edit Matiere</h1>

    {{ include('matiere/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_matiere_index') }}">back to list</a>

    {{ include('matiere/_delete_form.html.twig') }}
{% endblock %}

templates/matiere/index.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ path('app_admin_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
    <a href="{{ path('app_professeur_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des professeurs</a>
    <a href="{{ path('app_stagiaire_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des stagiaires</a>
    <a href="{{ path('app_matiere_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des matières</a>
    <a href="{{ path('app_stage_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des stages</a>
{% endblock %}
{% block body %}
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th>Code matière</th>
                <th>Libellé</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for matiere in matieres %}
                <tr>
                    <td>{{ matiere.codeMatiere }}</td>
                    <td>{{ matiere.libelle }}</td>
                    <td>{{ matiere.description }}</td>
                    <td>
                        <a href="{{ path('app_matiere_edit', {'id': matiere.id}) }}" class="btn btn-outline-dark m-2">Modifier</a>
                        {{ include('matiere/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Pas de stage de proposés sur la plateforme</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

templates/matiere/new.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ path('app_admin_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
{% endblock %}
{% block body %}
    <div class="container">
        <h2 class="mb-4 text-center">Création d'une matière</h2>

        <div>
            {{ form_start(form) }}
                {{ form_row(form.libelle) }}
                {{ form_row(form.description) }}
            <button class="btn btn-outline-dark">{{ button_label|default('Créer') }}</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/matiere/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matiere{% endblock %}

{% block body %}
    <h1>Matiere</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ matiere.id }}</td>
            </tr>
            <tr>
                <th>Code_matiere</th>
                <td>{{ matiere.codeMatiere }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ matiere.libelle }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ matiere.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_matiere_index') }}">back to list</a>

    <a href="{{ path('app_matiere_edit', {'id': matiere.id}) }}">edit</a>

    {{ include('matiere/_delete_form.html.twig') }}
{% endblock %}