src/Entity/Stage.php
<?php

namespace App\Entity;

use App\Repository\StageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: StageRepository::class)]
class Stage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $code_stage = null;

    #[ORM\Column(length: 60)]
    private ?string $libelle = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    /**
     * @var Collection<int, Matiere>
     */
    #[ORM\ManyToMany(targetEntity: Matiere::class, mappedBy: 'stages', cascade: ['persist'])]
    private Collection $matieres;

    /**
     * @var Collection<int, Stagiaire>
     */
    #[ORM\ManyToMany(targetEntity: Stagiaire::class, inversedBy: 'stages', cascade: ['persist'])]
    private Collection $stagiaires;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    /**
     * @var Collection<int, Professeur>
     */
    #[ORM\ManyToMany(targetEntity: Professeur::class, inversedBy: 'stages', cascade: ['persist'])]
    private Collection $professeurs;

    public function __construct()
    {
        $this->matieres = new ArrayCollection();
        $this->stagiaires = new ArrayCollection();
        $this->professeurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeStage(): ?string
    {
        return $this->code_stage;
    }

    public function setCodeStage(string $code_stage): static
    {
        $this->code_stage = $code_stage;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    /**
     * @return Collection<int, Matiere>
     */
    public function getMatieres(): Collection
    {
        return $this->matieres;
    }

    public function addMatiere(Matiere $matiere): self
    {
        if (!$this->matieres->contains($matiere)) {
            $this->matieres->add($matiere);
            $matiere->addStage($this);
        }

        return $this;
    }

    public function removeMatiere(Matiere $matiere): self
    {
        if ($this->matieres->removeElement($matiere)) {
            $matiere->removeStage($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): static
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->add($stagiaire);
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): static
    {
        $this->stagiaires->removeElement($stagiaire);

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, Professeur>
     */
    public function getProfesseurs(): Collection
    {
        return $this->professeurs;
    }

    public function addProfesseur(Professeur $professeur): static
    {
        if (!$this->professeurs->contains($professeur)) {
            $this->professeurs->add($professeur);
        }

        return $this;
    }

    public function removeProfesseur(Professeur $professeur): static
    {
        $this->professeurs->removeElement($professeur);

        return $this;
    }
}

src/Form/StageType.php
<?php

namespace App\Form;

use App\Entity\Matiere;
use App\Entity\Professeur;
use App\Entity\Stage;
use App\Entity\Stagiaire;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle')
            ->add('description')
            ->add('date_debut', DateType::class, [
                'label' => 'Date de début',
                'widget' => 'choice',
                'format' => 'dd/MM/yyyy',
                'placeholder' => [
                    'year' => 'Année',
                    'month' => 'Mois',
                    'day' => 'Jour',
                ],
                'required' => true,
            ])
            ->add('date_fin', DateType::class, [
                'label' => 'Date de fin',
                'widget' => 'choice',
                'format' => 'dd/MM/yyyy',
                'placeholder' => [
                    'year' => 'Année',
                    'month' => 'Mois',
                    'day' => 'Jour',
                ],
                'required' => true,
            ])
            ->add('matieres', EntityType::class, [
                'class' => Matiere::class,
                'label' => 'Matières',
                'choice_label' => function(Matiere $matiere) {
                    return $matiere->getLibelle() . ' (' . $matiere->getCodeMatiere() . ')';
                },
                'multiple' => true,
                'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Stage::class,
        ]);
    }
}

src/Controller/StageController.php
<?php

namespace App\Controller;

use App\Entity\Professeur;
use App\Entity\Stage;
use App\Entity\Stagiaire;
use App\Form\ParticipantType;
use App\Form\StageType;
use App\Repository\StageRepository;
use App\Repository\StagiaireRepository;
use App\Service\GenerateCode;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class StageController extends AbstractController
{
    #[Route('/stage', name: 'app_stage_index', methods: ['GET'])]
    public function index(StageRepository $stageRepository, StagiaireRepository $stagiaireRepository): Response
    {
        $professeurs = [];
        $matieres = [];
        $stagiaires = [];

        foreach ($stageRepository->findAll() as $stage) {
            $professeurs[$stage->getId()] = [];
            foreach ($stage->getProfesseurs() as $professeur) {
                $professeurs[$stage->getId()][] = $professeur->getNom() . " " . $professeur->getPrenom();
            }
        }

        foreach ($stageRepository->findAll() as $stage) {
            $matieres[$stage->getId()] = [];
            foreach ($stage->getMatieres() as $matiere) {
                $matieres[$stage->getId()][] = $matiere->getLibelle();
            }
        }

        foreach ($stageRepository->findAll() as $stage) {
            array_push($stagiaires, $stagiaireRepository->findStagiaireByStage($stage));
        }

        return $this->render('stage/index.html.twig', [
            'stages' => $stageRepository->findAll(),
            'professeurs' => $professeurs,
            'stagiaires' => count($stagiaires),
            'matieres' => $matieres,
        ]);
    }

    #[Route('/stage/ajout_stage', name: 'app_stage_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, GenerateCode $code): Response
    {
        $stage = new Stage();

        $form = $this->createForm(StageType::class, $stage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $stage->setCodeStage($code->code());

            $matieres = $form->get('matieres')->getData();
            foreach ($matieres as $matiere) {
                $stage->addMatiere($matiere);
                $matiere->addStage($stage);
            }

            $entityManager->persist($stage);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_dashboard', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('stage/new.html.twig', [
            'stage' => $stage,
            'form' => $form,
        ]);
    }


    #[Route('/stage/{id}', name: 'app_stage_show', methods: ['GET'])]
    public function show(Stage $stage): Response
    {
        $matieres = $stage->getMatieres();
        $professeurs = $stage->getProfesseurs();
        $stagiaires = $stage->getStagiaires();

        $libelleMatiere = [];
        $libelleProfesseur = [];
        $libelleStagiaire = [];

        foreach ($matieres as $matiere) {
            $libelleMatiere[] = $matiere->getLibelle();
        }

        foreach ($professeurs as $professeur) {
            $libelleProfesseur[] = $professeur->getNom() . " " . $professeur->getPrenom();
        }

        foreach ($stagiaires as $stagiaire) {
            $libelleStagiaire[] = $stagiaire->getNom() . " " . $stagiaire->getPrenom();
        }

        return $this->render('stage/show.html.twig', [
            'stage' => $stage,
            'matieres' => $libelleMatiere,
            'professeurs' => $libelleProfesseur,
            'stagiaires' => $libelleStagiaire,
        ]);
    }

    #[Route('/stage/{id}/participant', name: 'app_stage_show_participant', methods: ['GET'])]
    public function showParticipant(Stage $stage): Response
    {
        $matieres = $stage->getMatieres();
        $professeurs = $stage->getProfesseurs();
        $stagiaires = $stage->getStagiaires();

        $libelleMatiere = [];
        $libelleProfesseur = [];
        $libelleStagiaire = [];

        foreach ($matieres as $matiere) {
            $libelleMatiere[] = $matiere->getLibelle();
        }

        foreach ($professeurs as $professeur) {
            $libelleProfesseur[] = $professeur->getNom() . " " . $professeur->getPrenom();
        }

        foreach ($stagiaires as $stagiaire) {
            $libelleStagiaire[] = $stagiaire->getNom() . " " . $stagiaire->getPrenom();
        }

        return $this->render('stage/show_participant.html.twig', [
            'stage' => $stage,
            'matieres' => $libelleMatiere,
            'professeurs' => $libelleProfesseur,
            'stagiaires' => $libelleStagiaire,
        ]);
    }

    #[Route('/stage/{id}/modification_stage', name: 'app_stage_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Stage $stage, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StageType::class, $stage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $matieres = $form->get('matieres')->getData();
            foreach ($matieres as $matiere) {
                $stage->addMatiere($matiere);
                $matiere->addStage($stage);
            }

            $entityManager->persist($stage);
            $entityManager->flush();

            return $this->redirectToRoute('app_stage_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('stage/edit.html.twig', [
            'stage' => $stage,
            'form' => $form,
        ]);
    }

    #[Route('/stage/{id}/suppression_stage', name: 'app_stage_delete', methods: ['POST'])]
    public function delete(Request $request, Stage $stage, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $stage->getId(), $request->request->get('_token'))) {
            $entityManager->remove($stage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_stage_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/stage/{id}/ajout_participant', name: 'app_stage_participant', methods: ['GET', 'POST'])]
    public function ajoutParticipantStage(Request $request, Stage $stage, EntityManagerInterface $entityManager): Response
    {
        $matieresStage = $stage->getMatieres();
        $professeursForm = $entityManager->getRepository(Professeur::class)->findProfesseursByMatieres($matieresStage);

        $stagiairesForm = $entityManager->getRepository(Stagiaire::class)->findAll();

        $form = $this->createForm(ParticipantType::class, null, [
            'professeurs' => $professeursForm,
            'stagiaires' => $stagiairesForm,
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $professeurs = $form->get('professeurs')->getData();
            foreach ($professeurs as $professeur) {
                $stage->addProfesseur($professeur);
                $professeur->addStage($stage);
            }

            $stagiaires = $form->get('stagiaires')->getData();
            foreach ($stagiaires as $stagiaire) {
                $stage->addStagiaire($stagiaire);
                $stagiaire->addStage($stage);
            }

            $entityManager->persist($stage);
            $entityManager->flush();

            return $this->redirectToRoute('app_stage_index');
        }

        return $this->render('stage/add_participant.html.twig', [
            'form' => $form->createView(),
        ]);
    }


}

templates/stage/_delete_form.html.twig
<form method="post" action="{{ path('app_stage_delete', {'id': stage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stage.id) }}">
    <button class="btn btn btn-danger">Supprimer</button>
</form>

templates/stage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/stage/add_participant.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    <a href="{{ path('app_admin_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
    <a href="{{ path('app_stage_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Retour à la liste</a>
{% endblock %}

{% block body %}
    <div class="container">
        <h4 class="text-center">Ajouter des participants au stage</h4>

        {{ form_start(form) }}
        <div>
            {{ form_row(form.professeurs) }}
        </div>
        <div>
            {{ form_row(form.stagiaires) }}
        </div>

        <button type="submit" class="btn btn-primary">Valider</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/stage/edit.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ path('app_admin_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
    <a href="{{ path('app_stage_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Retour à la liste</a>
{% endblock %}
{% block body %}
<div class="container">
    <h4 class="text-center">Modification du stage</h4>
    {{ form_start(form) }}
        {{ form_row(form.libelle) }}
        {{ form_row(form.description) }}
        {{ form_row(form.date_debut) }}
        {{ form_row(form.date_fin) }}
        {{ form_row(form.matieres) }}
        <button class="btn btn-outline-dark">{{ button_label|default('Sauvegarder') }}</button>
    {{ form_end(form) }}
</div>

{% endblock %}

templates/stage/index.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ path('app_admin_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
    <a href="{{ path('app_professeur_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des professeurs</a>
    <a href="{{ path('app_stagiaire_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des stagiaires</a>
    <a href="{{ path('app_matiere_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des matières</a>
    <a href="{{ path('app_stage_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Gestion des stages</a>
{% endblock %}
{% block body %}
<div class="container">
    <div class="row g-4">
        {% for stage in stages %}
            <div class="col-md-3 mb-4">
                <div class="card shadow-sm" style="width: 100%;">
                    <span
                            class="badge"
                            style="position: absolute; top: 10px; right: 10px; font-size: 10px; padding: 10px; background-color: #ffc591;">
                    Code : {{ stage.codeStage }}
                    </span>
                    <div class="card-body">
                        <h5 class="card-title">{{ stage.libelle }}</h5>
                        <p class="card-text">
                            Date de début : {{ stage.dateDebut ? stage.dateDebut|date('d-m-Y') : '' }}
                            Date de fin : {{ stage.dateFin ? stage.dateFin|date('d-m-Y') : '' }}
                        </p>
                        <a href="{{ path('app_stage_show', {'id' : stage.id}) }}" class="btn btn-outline-dark btn-sm">Voir plus</a>
                    </div>
                    <div class="card-footer text-muted text-center">
                        {% if matieres[stage.id] is empty %}
                            <p>Aucune matière associée</p>
                        {% else %}
                            <p>Matières : {{ matieres[stage.id]|join(', ') }}</p>
                        {% endif %}

                        {% if professeurs[stage.id] is empty %}
                            <p>Aucun professeur associé</p>
                        {% else %}
                            <p>Professeurs : {{ professeurs[stage.id]|join(', ') }}</p>
                        {% endif %}

                        {% if stage.stagiaires is empty %}
                            <p>Aucun stagiaire associé</p>
                        {% else %}
                            <p>Nombre de stagiaires : {{ stage.stagiaires|length }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

templates/stage/new.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ path('app_admin_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="mb-4 text-center">Création d'un stage</h2>

        <div>
            {{ form_start(form) }}
                {{ form_row(form.libelle) }}
                {{ form_row(form.description) }}
                {{ form_row(form.date_debut) }}
                {{ form_row(form.date_fin) }}
                {{ form_row(form.matieres) }}
            <div class="card border-warning text-center p-2 m-4">
                Pensez à y inscrire des professeurs et stagiaires dans "Gestion des matières et stages".
            </div>

            <button class="btn btn-outline-dark">{{ button_label|default('Créer') }}</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/stage/show.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ path('app_admin_dashboard') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
    <a href="{{ path('app_stage_index') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Retour à la liste</a>
{% endblock %}
{% block body %}
    <div class="container">
        <table class="table">
            <tbody>
            <tr>
                <th>Code stage</th>
                <td>{{ stage.codeStage }}</td>
            </tr>
            <tr>
                <th>Libellé</th>
                <td>{{ stage.libelle }}</td>
            </tr>
            <tr>
                <th>Description du stage</th>
                <td>{{ stage.description }}</td>
            </tr>
            <tr>
                <th>Date de début</th>
                <td>{{ stage.dateDebut ? stage.dateDebut|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Date de fin</th>
                <td>{{ stage.dateFin ? stage.dateFin|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Matières</th>
                <td>
                    {{ matieres|join(", ") }}
                </td>
            </tr>
            <tr>
                <th>Professeurs</th>
                <td>
                    {{ professeurs|join(", ") }}
                </td>
            </tr>
            <tr>
                <th>Stagiaires</th>
                <td>
                    {{ stagiaires|join(", ") }}
                </td>
            </tr>
            </tbody>
        </table>

        <div class="">
            <a href="{{ path('app_stage_edit', {'id': stage.id}) }}" class="btn btn-outline-dark mb-2">Modifier</a>
            <a href="{{ path('app_stage_participant', {'id': stage.id}) }}" class="btn btn-outline-dark mb-2">Ajouter des participants</a>
            {{ include('stage/_delete_form.html.twig') }}
        </div>

    </div>


{% endblock %}

templates/stage/show_participant.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <a href="{{ app.request.headers.get('referer') }}" class="nav-item btn" style="background-color: #FFDAB9;margin-right: 10px;">Menu</a>
{% endblock %}
{% block body %}
    <div class="container">
        <table class="table">
            <tbody>
            <tr>
                <th>Code stage</th>
                <td>{{ stage.codeStage }}</td>
            </tr>
            <tr>
                <th>Libellé</th>
                <td>{{ stage.libelle }}</td>
            </tr>
            <tr>
                <th>Description du stage</th>
                <td>{{ stage.description }}</td>
            </tr>
            <tr>
                <th>Date de début</th>
                <td>{{ stage.dateDebut ? stage.dateDebut|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Date de fin</th>
                <td>{{ stage.dateFin ? stage.dateFin|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Matières</th>
                <td>
                    {{ matieres|join(", ") }}
                </td>
            </tr>
            <tr>
                <th>Professeurs</th>
                <td>
                    {{ professeurs|join(", ") }}
                </td>
            </tr>
            <tr>
                <th>Stagiaires</th>
                <td>
                    {{ stagiaires|join(", ") }}
                </td>
            </tr>
            </tbody>
        </table>
    </div>


{% endblock %}